### ISSUE TITLE
Redirect Conflict with Carpet Mod

### ISSUE THREAD

**Issue by the-arkhive** [Trikzon/Survival-Debug-Stick#2]
I've already let the Carpet mod authors know this as well, but there is a redirect conflict between this mod and carpet mod that causes server crash. I can give you the full crash report if you like, but this is the specific line:

`[14:49:35] [Server thread/WARN]: @Redirect conflict. Skipping carpet.mixins.json:ServerPlayerInteractionManager_ghostBlocksMixin->@Redirect::redirect$noCheatBlockBreakSpeed (...) with priority 1000, already redirected by survivaldebugstick.mixins.json:ServerPlayerInteractionManagerMixin->@Redirect::redirect$calcBlockBreakingDeltaProxy (...) with priority 1000`

**Comment by Trikzon** [comment]
I no longer mixin to that class in 1.15.2+ so it should be fine in those versions. I don't really plan on doing that for the 1.14.4 version because its a pain to switch my workspace... but reopen this issue if you still want this fixed :)
